### ISSUE TITLE
GTask is unusable

### ISSUE THREAD

**Issue by v1993** [pavouk/lgi#150]
Please, look at this:
    > lgi = require 'lgi'
    > gio = lgi.Gio
    > a = gio.Task(nil, gio.Cancellable(), function() print('Yay!!!') end)
    > print(a.run_in_thread)
    [string "print(a.run)"]:1: Gio.Task: no 'run_in_thread'
    ...

**Comment by TingPing** [comment]
Should be fixed by this upstream: https://bugzilla.gnome.org/show_bug.cgi?id=693576

**Comment by psychon** [comment]
Also, there is no `g_task_run`: https://developer.gnome.org/gio/stable/GTask.html#g-task-run
So whatever the problem should be, this is not due to lgi.

**Comment by pavouk** [comment]
lgi should be thread-safe in most use cases, so after the fix lands in glib, this should start to work.

**Comment by TingPing** [comment]
It might help move it along if somebody from lgi tests it and insures it works here too.

**Comment by v1993** [comment]
It still isn't working. Bug: https://gitlab.gnome.org/GNOME/glib/issues/668

**Comment by v1993** [comment]
Is this outdated now with #226?

**Comment by v1993** [comment]
This function is there in last Gtk/GLib, closing this.
